---
driver:
  name: docker
provisioner:
  name: shell

platforms:
  - name: ubuntu-16.04
    driver:
      name: docker
      volume:
        - <%= ENV['PWD'] %>:/tmp/kitchen
      #provision_command:
      #  - apt-get update

#  - name: ubuntu-16.04
 ## Finally add support to RHEL platforms
 #- name: centos-7.0


verifier:
  name: inspec
  sudo: true

suites:

 - name: master
   #provisioner:
   #  script: tests/bootstrap.sh master

 - name: minion
   #provisioner:
   #  script: tests/bootstrap.sh minion
