---
driver:
  name: docker
  use_sudo: true

provisioner:
  name: shell
  use_sudo: true

platforms:
  - name: ubuntu-14.04
    driver:
      name: docker
      volume:
        - <%= ENV['PWD'] %>:/tmp/kitchen

  #- name: ubuntu-16.04
    #driver:
      #name: docker
      #volume:
        #- <%= ENV['PWD'] %>:/tmp/kitchen

 ## Finally add support to RHEL platforms
 #- name: centos-7.0


verifier:
  name: inspec
  sudo: true

suites:

 - name: master
   provisioner:
     script: test/setup.sh

 - name: minion
   provisioner:
     script: test/setup.sh
